version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: 'projstreaming'
    restart: always
    volumes:
      - postgres-disk:/var/lib/postgresql/database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Aurean22
      POSTGRES_DB: projstreaming

volumes:
  postgres-disk: